name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install azure-identity==1.15.0
        pip install openai==1.6.1
        pip install azure-search-documents==11.4.0b6
        pip install azure-storage-blob==12.17.0
        pip install python-dotenv==1.0.0
        pip install azure-cosmos==4.5.0
        pip install quart==0.19.4
        pip install uvicorn==0.24.0
        pip install aiohttp==3.9.2
        pip install gunicorn==20.1.0
        pip install quart-session==3.0.0
        pip install pymssql==2.3.0
        pip install httpx==0.27.0
        pip install flake8==7.1.1
        pip install black==24.8.0
        pip install autoflake==2.3.1
        pip install isort==5.13.2
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
